title: "mgy583博客"
description: "Powered by GitHub Pages + Jekyll"
theme: minima
lang: zh-CN
author: "mgy583"
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
